### ISSUE TITLE
API giving stacktrace

### ISSUE THREAD

**Issue by sanjuroj** [hackoregon/transportation-backend#37]
http://localhost:8000/transport/nearby/?nearby_list=yes

Gives a stack trace because of an uncaught error.

**Comment by MikeTheCanuck** [comment]
I saw a different exception from the /conflicts endpoint, but /features ran fine.

**Comment by leobender** [comment]
The build was never rebuilt after I updated "DEBUG = False" in the S3 bucket earlier today, so the live site was still running with "DEBUG = True".  I just redeployed the container and now it is giving a 500 error on the live site: http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/transport/nearby/?nearby_list=yes

**Comment by MikeTheCanuck** [comment]
500 error is the "polite" version of the exceptions and stack traces we see when DEBUG=True, so it's not like this is worse - just that it's harder to decipher.
