### ISSUE TITLE
502 Bad Gateway on the /transport/conflicts endpoint on production server (instantaneous failure)

### ISSUE THREAD

**Issue by leobender** [hackoregon/transportation-backend#44]
- 502 appears to be coming from the AWS load balancer. 
- Cloudwatch is not logging any issues with the transport container
- Endpoint is functional but slow when running in a local container

URL:
http://hacko-integration-658279555.us-west-2.elb.amazonaws.com/transport/conflicts/

**Comment by znmeb** [comment]
which endpoint is it? the "transport/features" endpoint takes a couple of minutes to gather all of them! If we're going to use that, can we cache it? Data will not be changing!!!

**Comment by sanjuroj** [comment]
It's the conflicts endpoint that's not working.  The features endpoint will be used with a set of filters that makes it much faster to load.

**Comment by znmeb** [comment]
would having a PgAdmin4 server in the instance help troubleshoot? I've got a way to do that now.

**Comment by sanjuroj** [comment]
Tony's looking at the problem, I think he'll let us know if he needs something.  Good to know though.

**Comment by znmeb** [comment]
@sanjuroj @MikeTheCanuck Is this still open?

**Comment by sanjuroj** [comment]
Nope.  It was a memory issue one the server, and they bumped up the memory.  I'm have no idea what the deployment looks like now so I'll close this.  They can open a new ticket if they have a problem.
