### ISSUE TITLE
Github user nam20485 lack commit access to this repo

### ISSUE THREAD

**Issue by nam20485** [hackoregon/transportation-backend#50]
As a person desiring to resolve issues logged in this repo, I would like to be able to resolve the issues by possessing the access permissions required to allow me to commit code changes.

**Comment by MikeTheCanuck** [comment]
I don’t have that ability Nathan, but in the interim you *could* also fork the repo and PR a fix, so at least the work would be ready for those privileged enough (and available to anyone who’s also looking at the code

**Comment by znmeb** [comment]
What changes need to be made to the back end? Did I miss a Slack discussion or some emails?

**Comment by znmeb** [comment]
Speaking of which, does anyone have contact info for Sanjuro? I just looked at the open issues and I'm pretty sure we did all of that before demo day. ;-)

**Comment by nam20485** [comment]
@znmeb No you did not miss any conversation per se, but I did notice @MikeTheCanuck 's issue #49 and was able to suggest a resolution and talk briefly with him about. I created a branch "issue49" that contains a .sh script that should resolve the error he is seeing in the issue.

**Comment by nam20485** [comment]
@MikeTheCanuck Understood. I have now created a new branch and PR. I think that I may already have permissions, possibly due to my existing membership in the HackOregon github team. Either way I do have sufficient privileges to create branches and PRs on this repo.

**Comment by nam20485** [comment]
Closing issue as unnecessary.

**Comment by znmeb** [comment]
I can merge it ... but is there a way to test that it fixes the problem and doesn't cause new ones? Do we have the Travis set up to do that?

**Comment by nam20485** [comment]
I do see a travis project under the HackOregon workspace that appears like it was used for this repo but it is currently in the deactivated state. (https://travis-ci.org/hackoregon/transportation-backend)

**Comment by znmeb** [comment]
If nothing's getting deployed I don't see any point in re-enabling Travis - it'll just mean more work. I sent a DM on the Slack to @sanjuroj to see if we can close all the open issues.

**Comment by znmeb** [comment]
I just looked at the team settings - in theory both @nam20485 and @MikeTheCanuck had write access. I bumped that up to admin.

**Comment by sanjuroj** [comment]
I'm curious, was there a decision made to continue with this project?  There are  lot of things that could be worked on and I'm not sure that the current Github issues are a really good list of priorities.  I suspect it's not worth working on these Github issues without a review of priorities and desired functionality.  That said, you're welcome to do whatever you want of course  :-)

**Comment by znmeb** [comment]
I'm not aware of any decision - I should probably ask Megan what the plan is.

**Comment by meganmckissack** [comment]
Hi all!  There's no current work planned on this at the moment.  @nam20485 is the TA for our current DevOps class and was on the transportation team last season; I think he's looking at how our work was set up and found something he could fix.  I'm currently trying to work on processes documentation, there's a small team working on fixing civic-wide front-end issues, and I think a few people (ie @MikeTheCanuck) are looking at cleaning up old open issues, hence some of the activity.  There will be a new project season starting soonish but right now, no real work to be done unless people are looking to tidy projects up.  Thanks for all your help!

**Comment by znmeb** [comment]
I don't mind tidying up this one. ;-)

**Comment by MikeTheCanuck** [comment]
Yeah, I took a sweep through all the backend projects to see if they were building as well as they did when we left them last May, and where I spotted anything less than smooth I filed issues for myself or anyone else who wanted to take a look.

Whether the projects are going to be revived is an open question; but if they're in a broken state, that's a strike against them I'd prefer to alleviate wherever possible.  (Not to mention, with the nationalization of Hack, that ought to bring additional attention from folks who weren't part of the projects, and I'd like to present as much working code - or maintained projects at minimum - for any strangers who stumble in.)

**Comment by znmeb** [comment]
@MikeTheCanuck My sentiments exactly! Especially since I have all this free time (at least till the projects start up again) ;-)

**Comment by sanjuroj** [comment]
That sounds totally reasonable.  I don't have much time to spend on this at the moment but feel free to shoot me questions if I've written something particularly cryptic that you want information on.
